### ISSUE TITLE
今后考虑开个python3的分支吗？

### ISSUE THREAD

**Issue by vc12345679** [eastossifrage/pyblog#1]
RT

**Comment by eastossifrage** [comment]
还没有这样的考虑，因为现在的 flask 对 python3 的支持还不够友好。

**Comment by vc12345679** [comment]
flask对python3支持没问题，有问题的是misaka，python3下安装费了一番功夫。
我后来也写了个基于python3 flask的markdown[博客系统](https://github.com/vc12345679/fmblog)，用mistune做的markdown parser，目前试下来没大毛病。

**Comment by eastossifrage** [comment]
mistune 是个好东西啊.这个回头得好好学学.

**Comment by frostming** [comment]
试下[Marko](https://github.com/frostming/marko)咯，扩展语法简直不要更简单，支持CommonMark/GFM哦，当然代价是比mistune慢得多

我自己用Flask+Marko搭的博客：https://frostming.com ([GitHub](https://github.com/frostming/frostming.com))
