### ISSUE TITLE
安装教程里有个命令Plugin.insert_plugins()

### ISSUE THREAD

**Issue by zy1620454507** [eastossifrage/pyblog#2]
安装教程里有个命令Plugin.insert_plugins(),Plugin在哪个包里，怎么导入？

**Comment by eastossifrage** [comment]
对不起，是我的失误，升级到 2.0 之后，已经不需要这个插件的安装了。这个命令不需要执行了。

**Comment by eastossifrage** [comment]
对不起，是我的失误，升级到 2.0 之后，已经不需要这个插件的安装了。这个命令不需要执行了。

zy1620454507 <notifications@github.com> 于2018年8月10日周五 上午11:35写道：
